//! Bindings to liblogosdelivery, generated by nim-ffi's `genBindings()` from the
//! vendor's `library/liblogosdelivery.nim`.
//!
//! The generated sources are consumed in place rather than copied, so
//! regenerating them in the vendor flows through here directly. `api.rs`
//! resolves its siblings through `super::`, so the three have to stay sibling
//! modules of this root.

#[path = "../vendor/library/rust_bindings/src/ffi.rs"]
mod ffi;
#[path = "../vendor/library/rust_bindings/src/types.rs"]
mod types;
#[path = "../vendor/library/rust_bindings/src/api.rs"]
mod api;

pub use api::*;
pub use types::*;
